# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: mge-service unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --skip-lock
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pipenv run pytest src/tests/unit_tests/cp.py
    - name: Test coverage
      run: |
        pipenv run pytest --cov=mge-service src/tests/unit_tests/cp.py
    - name: Check coverage threshold
      run: |
        COVERAGE_THRESHOLD=80  # Adjust this threshold as needed
        coverage=$(pipenv run pytest --cov=mge-service --cov-report=xml | grep -oP 'total="(\d+)"' | sed 's/[^0-9]*//g')
        if [ "$coverage" -lt "$COVERAGE_THRESHOLD" ]; then
          echo "Coverage is below threshold. Expected at least $COVERAGE_THRESHOLD%, but got $coverage%."
          exit 1
        fi